kind: pipeline
name: default

steps:
- name: install
  image: ruby:3.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle install

- name: test
  image: ruby:3.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rspec spec

- name: build
  image: ruby:3.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rake build
  # when:
  #   ref:
  #   - refs/tags/*

- name: deploy
  image: ruby:3.0
  environment:
    RUBYGEMS_APIKEY:
      from_secret: rubygems_apikey
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - mkdir ~/.gem
  - 'echo -e "---\n:rubygems_api_key: $RUBYGEMS_APIKEY" > ~/.gem/credentials'
  - chmod 0600 ~/.gem/credentials
  - gem push pkg/*.gem
  # when:
  #   ref:
  #   - refs/tags/*

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
type: exec
name: docker

steps:
- name: build
  commands:
  - docker build . -t example
- name: run
  commands:
  - docker run example
