kind: pipeline
name: default

steps:
- name: install
  image: ruby
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle install

- name: test
  image: ruby
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rspec spec

- name: build
  image: ruby
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rake build
  when:
    branch:
    - main

- name: deploy
  image: ruby
  environment:
    RUBYGEMS_APIKEY:
      from_secret: rubygems_apikey
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - mkdir ~/.gem
  - 'echo -e "---\n:rubygems_api_key: $RUBYGEMS_APIKEY" > ~/.gem/credentials'
  - chmod 0600 ~/.gem/credentials
  - gem push pkg/*.gem
  when:
    ref:
    - refs/tags/*

volumes:
- name: bundle
  temp: {}