version: '2'

services:
  web-api:
    build: ./web_api
    hostname: spectre-web
    ports:
      - 4567:4567

  mysql:
    image: mysql
    hostname: spectre-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev

  postgres:
    image: postgres
    hostname: spectre-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev

  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    hostname: spectre-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD_ACCESS=true
      - USER_NAME=developer
      - USER_PASSWORD=dev
    ports:
      - 2222:2222

  ftp-server:
    image: delfer/alpine-ftp-server
    hostname: spectre-ftp
    ports:
      - '2121:21'
      - 21000-21010:21000-21010
    environment:
      - USERS=developer|dev
