name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Check style
      run: bundle exec rubocop

    - name: Run unit tests
      run: bundle exec rspec

    - name: Build 
      run: bundle exec gem build

