name: Docker

on:
  # Manually publish
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: docker.io
  DOCKER_ACCOUNT: cneubauer
  IMAGE_NAME: spectre

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${DOCKER_ACCOUNT} -p ${DOCKER_TOKEN}
        env:
          DOCKER_TOKEN: "${{secrets.DOCKER_TOKEN}}"

      - name: Docker Build
        run: docker build -t ${DOCKER_ACCOUNT}/${IMAGE_NAME}:${GITHUB_REF_NAME#*} -t ${DOCKER_ACCOUNT}/${IMAGE_NAME}:latest .

      - name: Docker Push
        run: docker push ${DOCKER_ACCOUNT}/${IMAGE_NAME} --all-tags